### ISSUE TITLE
[Question] Does this work for webextensions?

### ISSUE THREAD

**Issue by GTP95** [debug-js/debug#907]
Greetings,

I'm trying to use this library in the context of a browser extension. Copying form the examples, I put the following code inside my ContentScript:
```JS
const debugOutput = require("debug")("http"),
  http = require("http"),
  name = "PostGuard Webextension";

debugOutput.enable(name);
debugOutput("booting %o", name);
```
But when I execute the extension, I get the following error in the browser's console: `Uncaught TypeError: debugOutput.enable is not a function`. What am I doing wrong?
Thank you for your help,

GTP

**Comment by Qix-** [comment]
Please have a second look at the README because you're missing a few concepts. `enable()` is to enable namespaces and is located on the top-level `debug` package - `require('debug').enable(...)`. It's not meant for fancy titles or whatever you think it is - debug uses `namespaces:like:this` to modularize output and allow you to enable just parts of your application that you're interested in logging.

If you just want to enable a single logger, use `const debug = require('debug')('...'); debug.enabled = true`.

Hope that helps!

**Comment by kuzdogan** [comment]
I spent an hour how to accomplish this and my issue was I that "verbose" browser logs were not enabled in Chrome. In the README it states:

> In Chromium-based web browsers (e.g. Brave, Chrome, and Electron), the JavaScript console will—by default—only show messages logged by debug if the "Verbose" log level is enabled.

If you are using Webpack modes `webpack --mode=development` you can use 
```js
if (process.env.NODE_ENV === 'development') debug.enabled = true;
```
